ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-certmgr
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    douz.com/do-monitor: "true"
    douz.com/do-monitor-email: "douglas.barahona@me.com"
    douz.com/do-monitor-slack-webhook: "__SLACK_WEBHOOK__"
    douz.com/do-monitor-slack-channel: "#just-testing"
    douz.com/do-monitor-latency-threshold: "800"
    douz.com/do-monitor-latency-period: "5m"
    douz.com/do-monitor-ssl-expiry: "14"

  hosts:
    - host: douglasbarahona.me
      paths:
      - path: /
        pathType: Prefix
  tls:
    - hosts:
        - douglasbarahona.me
        - www.douglasbarahona.me
      secretName: douglasbarahona-me-cert

imagePullSecrets:
  - name: regcred

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: "80"
  minReplicas: "2"
  maxReplicas: "4"

php:
  image:
    repository: ghcr.io/10up/wp-php-fpm
    tag: "8.2-ubuntu"
    pullPolicy: Always

wpinit:
  image:
    repository: ghcr.io/10up/wp-services
    pullPolicy: Always

wordpress:
  environment_type: production
  image:
    repository: ghcr.io/douz/blogs-wp
    tag:
    pullPolicy: Always

  dbhost: mariadb.mariadb.svc.cluster.local
  dbuser: douz_wp
  dbpass: __DB_PASS__
  dbname: douz_wp

  table_prefix: "wp_"

  redis:
    enabled: true
    host: redis-master.redis-ns.svc.cluster.local
    port: 6379
    password: __REDIS_PASS__

  block_xmlrpc:
    enabled: false
    allow: none

  urls:
    - douglasbarahona.me
  title: "Douglas Barahona - Blog"

  custom_wp_config: |
    define( 'S3_UPLOADS_BUCKET', '__S3_UPLOADS_BUCKET__' );
    define( 'S3_UPLOADS_REGION', 'us-east-1' ); // the s3 bucket region (excluding the rest of the URL)
    define( 'S3_UPLOADS_KEY', '__S3_UPLOADS_KEY__' );
    define( 'S3_UPLOADS_SECRET', '__S3_UPLOADS_SECRET__' );
    define( 'S3_UPLOADS_BUCKET_URL', 'https://cdn.douglasbarahona.me' );