name: PHP Syntax Check, virus scan, and WP Plugin & Theme vulnerability scan

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build-plugins-and-theme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      
      - name: WordPress Scanner
        uses: ./.github/wp-scanner
        with:
          vuln_api_provider: 'wordfence'
          content_dir: './'
          wp_core_version: '6.4.3'
          composer_build: 'true'